In [1]:
import numpy as np
import pandas as pd
from prettytable import PrettyTable
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
import pickle

# Training Data

In [2]:
df = pd.read_csv("data/training.csv", usecols = [i for i in range(133)])

In [3]:
df.head(5)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [4]:
df.shape

(4920, 133)

In [5]:
df.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [6]:
t = PrettyTable(['Column', 'Nwgative', 'Positive'])
single_value_col = []

for col in df.columns[:132]:    
    try:
        t.add_row([col, df[col].value_counts()[0], df[col].value_counts()[1]])
    except:
        single_value_col.append(col)

In [7]:
t

+--------------------------------+----------+----------+
|             Column             | Nwgative | Positive |
+--------------------------------+----------+----------+
|            itching             |   4242   |   678    |
|           skin_rash            |   4134   |   786    |
|      nodal_skin_eruptions      |   4812   |   108    |
|      continuous_sneezing       |   4698   |   222    |
|           shivering            |   4812   |   108    |
|             chills             |   4122   |   798    |
|           joint_pain           |   4236   |   684    |
|          stomach_pain          |   4698   |   222    |
|            acidity             |   4698   |   222    |
|        ulcers_on_tongue        |   4812   |   108    |
|         muscle_wasting         |   4812   |   108    |
|            vomiting            |   3006   |   1914   |
|      burning_micturition       |   4704   |   216    |
|      spotting_ urination       |   4812   |   108    |
|            fatigue             |   2988   |   1932   |
|          weight_gain           |   4806   |   114    |
|            anxiety             |   4806   |   114    |
|      cold_hands_and_feets      |   4806   |   114    |
|          mood_swings           |   4692   |   228    |
|          weight_loss           |   4464   |   456    |
|          restlessness          |   4692   |   228    |
|            lethargy            |   4464   |   456    |
|       patches_in_throat        |   4812   |   108    |
|     irregular_sugar_level      |   4806   |   114    |
|             cough              |   4356   |   564    |
|           high_fever           |   3558   |   1362   |
|          sunken_eyes           |   4812   |   108    |
|         breathlessness         |   4470   |   450    |
|            sweating            |   4242   |   678    |
|          dehydration           |   4812   |   108    |
|          indigestion           |   4698   |   222    |
|            headache            |   3786   |   1134   |
|         yellowish_skin         |   4008   |   912    |
|           dark_urine           |   4350   |   570    |
|             nausea             |   3774   |   1146   |
|        loss_of_appetite        |   3768   |   1152   |
|      pain_behind_the_eyes      |   4800   |   120    |
|           back_pain            |   4692   |   228    |
|          constipation          |   4692   |   228    |
|         abdominal_pain         |   3888   |   1032   |
|           diarrhoea            |   4356   |   564    |
|           mild_fever           |   4566   |   354    |
|          yellow_urine          |   4806   |   114    |
|       yellowing_of_eyes        |   4104   |   816    |
|      acute_liver_failure       |   4806   |   114    |
|      swelling_of_stomach       |   4806   |   114    |
|      swelled_lymph_nodes       |   4572   |   348    |
|            malaise             |   4218   |   702    |
|  blurred_and_distorted_vision  |   4578   |   342    |
|             phlegm             |   4566   |   354    |
|       throat_irritation        |   4800   |   120    |
|        redness_of_eyes         |   4800   |   120    |
|         sinus_pressure         |   4800   |   120    |
|           runny_nose           |   4800   |   120    |
|           congestion           |   4800   |   120    |
|           chest_pain           |   4224   |   696    |
|       weakness_in_limbs        |   4812   |   108    |
|        fast_heart_rate         |   4686   |   234    |
|  pain_during_bowel_movements   |   4806   |   114    |
|      pain_in_anal_region       |   4806   |   114    |
|          bloody_stool          |   4806   |   114    |
|       irritation_in_anus       |   4806   |   114    |
|           neck_pain            |   4692   |   228    |
|           dizziness            |   4584   |   336    |
|             cramps             |   4806   |   114    |
|            bruising            |   4806   |   114    |
|            obesity             |   4692   |   228    |
|         

In [8]:
single_value_col

['fluid_overload']

In [9]:
df.drop(single_value_col, axis=1, inplace= True)

In [10]:
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 132 columns]

# Testing Data

In [11]:
test = pd.read_csv("data/testing.csv")

In [12]:
test.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   
3        1          0                     0                    0          0   
4        1          1                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   
3       0           0             0        0                 0  ...   
4       0           0             1        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze            prognosis  
0                  0     Fungal infection  
1                  0              Allergy  
2                  0                 GERD  
3                  0  Chronic cholestasis  
4                  0        Drug Reaction  

[5 rows x 133 columns]

In [13]:
test.drop(single_value_col, axis=1, inplace= True)

In [14]:
df.shape, test.shape

((4920, 132), (42, 132))

# Data Encoding

In [15]:
x_train = df.drop('prognosis', axis=1)
x_test = test.drop('prognosis', axis=1)

In [16]:
le = preprocessing.LabelEncoder()
y_train = le.fit_transform(df['prognosis'])
y_test = le.transform(test['prognosis'])

In [17]:
output = open('model/label_enccoder.pkl', 'wb')
pickle.dump(le, output)
output.close()

# Logistics Regression

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
logreg = LogisticRegression()

In [20]:
logreg.fit(x_train, y_train)

LogisticRegression()

In [21]:
y_pred = logreg.predict(x_test)

In [22]:
y_pred

array([15,  4, 16,  9, 14, 33,  1, 12, 17,  6, 23, 30,  7, 32, 28, 29,  8,
       11, 37, 40, 19, 20, 21, 22,  3, 36, 10, 34, 13, 18, 39, 26, 24, 25,
       31,  5,  0,  2, 38, 35, 27, 15])

In [23]:
confusion_matrix = confusion_matrix(y_test, y_pred)

In [24]:
print(confusion_matrix)

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [25]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         1
           8       1.00      1.00      1.00         1
           9       1.00      1.00      1.00         1
          10       1.00      1.00      1.00         1
          11       1.00      1.00      1.00         1
          12       1.00      1.00      1.00         1
          13       1.00      1.00      1.00         1
          14       1.00      1.00      1.00         1
          15       1.00      1.00      1.00         2
          16       1.00      1.00      1.00         1
          17       1.00    

In [26]:
print(accuracy_score(y_test, y_pred))

1.0


In [27]:
output = open('model/logreg_model.pkl', 'wb')
pickle.dump(logreg, output)
output.close()